#ifndef TEMPCONTROLCLASS_GLOBAL_H
#define TEMPCONTROLCLASS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TEMPCONTROLCLASS_LIBRARY)
#  define TEMPCONTROLCLASSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TEMPCONTROLCLASSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TEMPCONTROLCLASS_GLOBAL_H
